### ISSUE TITLE
升级OS X Yosemite 之后，ipfw被移除

### ISSUE THREAD

**Issue by xwartz** [xwartz/xwartz.github.com#2]
解决方法，https://github.com/basecamp/pow/issues/452

只是搬运工，给自己看：
1. 首先创建， `touch touch /etc/pf.anchors/com.pow`文件, 输入

``` sh
rdr pass on lo0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr pass on lo0 inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr pass on en0 inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443

```

_注意最后换行_
2.  打开， `vim /etc/pf.conf`文件，在 `rdr-anchor "com.apple/*"`之后添加：
`rdr-anchor "pow"`
在 `load anchor "com.apple" from "/etc/pf.anchors/com.apple"`之后添加：
`load anchor "pow" from "/etc/pf.anchors/com.pow"`
_注意最后换行_
3. 最后跑， `sudo pfctl -f /etc/pf.conf&&sudo pfctl -e` 就ok

**Comment by molecar** [comment]
按照上面的配置报：
No ALTQ support in kernel
ALTQ related functions disabled 
这个怎么解决？

**Comment by xwartz** [comment]
@molecar 你只能自己谷歌看看，我也不知道..
